//Do not modify this file, it will be autogenerated
export {default as Fuck } from './Fuck';
export {default as Home } from './Home';
export {default as NoMatchPage } from './NoMatchPage';
export {default as Nothing } from './Nothing';
export {default as Schedules } from './configuration/Schedules';
export {default as AddService } from './configuration/services/AddService';
export {default as ServiceDetail } from './configuration/services/ServiceDetail';
export {default as Services } from './configuration/services/Services';
export {default as System } from './system/System';
export {default as User } from './user/User';
